version: '3.8'
services:
  wiremock:
    image: wiremock/wiremock:latest
    container_name: wiremock-server
    ports:
      - "8089:8080"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
    command: --verbose