spring:
  profile:
    active: local
  application:
    name: CosmoCats
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8089/.well-known/jwks.json


application:
  security:
    api-key-header: "X-Api-Key"
    api-key: "cosmo-secret-key-123"
  supplier:
    service:
      url: http://localhost:8089
  rating-service:
    base-path: http://localhost:8089
    ratings: ${application.rating-service.base-path}/rating-service/v1/ratings
  feature:
    toggles:
      cosmo-kitty: true
      cat-products: false

---

spring:
  config:
    activate:
      on-profile: no-auth