spring:
  profile:
    active: local
  application:
    name: CosmoCats

application:
  supplier:
    service:
      url: http://localhost:8089
  rating-service:
    base-path: http://localhost:8089
    ratings: ${application.rating-service.base-path}/rating-service/v1/ratings
  feature:
    toggles:
      cosmoCats: true
      kittyProducts: false

---
spring:
  config:
    activate:
      on-profile: dev
application:
  feature:
    toggles:
      cosmoCats: true
      kittyProducts: false